<<<<<<< HEAD
server:
  port: 8080  # porta onde o gateway ficará ouvindo

=======
>>>>>>> 01df8f712ac05dedb02834abea5bda8087cd596f
spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
<<<<<<< HEAD
        - id: clientes-service
          uri: http://localhost:8081
          predicates:
            - Path=/clientes/**

        - id: produtos-service
          uri: http://localhost:8082
          predicates:
            - Path=/produtos/**

        # Você pode adicionar mais serviços aqui...

      default-filters:
        - AddResponseHeader=X-Gateway, SpringCloudGateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
=======
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/usuarios/**
        - id: client-service
          uri: http://localhost:8082
          predicates:
            - Path=/clientes/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/produtos/**

server:
  port: 8080
>>>>>>> 01df8f712ac05dedb02834abea5bda8087cd596f
