spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/usuarios/** 
        - id: client-service
          uri: http://localhost:8082
          predicates:
            - Path=/clientes/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/produtos/**

server:
  port: 8080
