server:
  port: 8080  # porta onde o gateway ficará ouvindo

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: clientes-service
          uri: http://localhost:8081
          predicates:
            - Path=/clientes/**

        - id: produtos-service
          uri: http://localhost:8082
          predicates:
            - Path=/produtos/**

        # Você pode adicionar mais serviços aqui...

      default-filters:
        - AddResponseHeader=X-Gateway, SpringCloudGateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
